baseurl = "https://noahrahm.com/"
contentdir = "content"
layoutdir = "layouts"
publishdir = "public"
title = "Noah Rahm"
canonifyurls = true

DefaultContentLanguage = "en"
theme = "site-theme"
metaDataFormat = "yaml"
pygmentsUseClasses = true
pygmentCodeFences = true
summaryLength = 12

[Params]
  logo = "favicon.png"
  favicon = "favicon.ico"
  dateFormat = "January 2, 2006"
  commit = false
  rss = true
  comments = false

[Author]
  name = "Noah Rahm"

[menu]
  [[menu.main]]
    name = "About"
    identifier = "about"
    url = "/about/"
    weight = 10

  [[menu.main]]
    name = "Work"
    identifier = "work"
    url = "/work/"
    weight = 30

  [[menu.main]]
    name = "Posts"
    identifier = "posts"
    url = "/posts/"
    weight = 40

  [[menu.main]]
    name = "Contact"
    identifier = "contact"
    url = "/contact/"
    weight = 50


[markup]
  [markup.tableOfContents]
    endLevel = 3
    startLevel = 2


[related]
    threshold = 0 
    includeNewer = true
    toLower = false

    [[related.indices]]
        name = "tags"
        weight = 100

    [[related.indices]]
        name = "date"
        weight = 10