baseurl = "https://noahrahm.com/"
contentdir = "content"
layoutdir = "layouts"
publishdir = "public"
title = "Noah Rahm"
canonifyurls = true

DefaultContentLanguage = "en"
theme = "site-theme"
metaDataFormat = "yaml"
pygmentsUseClasses = true
pygmentCodeFences = true
summaryLength = 12
disableKinds = ['categories']

[Params]
  logo = "favicon.png"
  favicon = "favicon.ico"
  dateFormat = "January 2, 2006"
  commit = false
  rss = true
  comments = false

[Author]
  name = "Noah Rahm"

[menu]
  [[menu.main]]
    name = "About"
    identifier = "about"
    url = "/about/"
    weight = 10

  [[menu.main]]
    name = "Work"
    identifier = "work"
    url = "/work/"
    weight = 30

  [[menu.main]]
    name = "Posts"
    identifier = "posts"
    url = "/posts/"
    weight = 40

